### PR TITLE
add sort groups individually option

### PR DESCRIPTION
**Pull request by DarthWixon**
I've added a local variable the user can set to turn on the changes - set it to true atm cos I've not properly tested it yet. Would set it to false by default I imagine.
The logic isn't fancy, I just replicated the individual group sort over every group in the raid. I'm sure there's a neater way, but will play more tomorrow.

TODO
- test to see if it works
- change the loop so it only sorts groups that are shown, rather than all of them

### CODE REVIEW

**Comment by Krealle** [comment]
(Sorry for wall of text xd)

You need to change the functionality of `getRaidGroupInfo` to build a proper table for `SORTED_RAID_GROUP` first.
Specifically this `for _, unit in pairs(F:GetUnitsInSubGroup(playerSubGroup)) do` needs to iterate entire raid.

Currently workflow essentially is:
1. Call `sortRaidFrames`
2. Which calls `local UNSORTED_RAID_GROUP = getRaidGroupInfo()` (We build an unsorted table with all, relevant, players)
3. Which calls `SORTED_RAID_GROUP = getSortedRaidGroup(UNSORTED_RAID_GROUP)` (We sort the table)
4. Which then calls `updateRaidFrames(SORTED_RAID_GROUP)` (We apply the changes to the frames)

The raid group table is currently 1D, which is fine for combined and singular group sorting. But for proper global raid sorting, the table should become 2D to mimic each subgroup structure, to ensure you assign players to the proper header.
Especially important when you start having mixed sub-group sizes. 

"Easiest" impl is prolly just to make the table globally 2D, with only one entry for own subgroup sort/combined sort.

And then make en entry for each subgroup for entire raid sort for non combined layout. I think you should be able to do something like this:

```
---@type table<Subgroup, table<Player>> -- new table structure
UNSORTED_RAID_GROUP = {}

-- if combined iterate F:IterateGroupMembers()
-- if subgroup only iterate F:GetUnitsInSubGroup(playerSubGroup)

-- if new global sort figure out the proper method to use most likely something like this:
-- should prolly just do both non combined sorts here and have a conditional for playerSubGroup 
for subgroup = 1, 8 -- think there is a number of groups fn you can call instead of using 8 else just use the groupFilter from combinedGroups) do
   UNSORTED_RAID_GROUP[subgroup] = {} -- remember to init the table

   -- IIRC F:GetUnitsInSubGroup will have extra looping when called like this, so maybe bad for performance
   -- So should prolly use F:IterateGroupMembers() I just can't recall what the key is, if it's subgroup thats perf, but need to confirm
   for _, unit in pairs(F:GetUnitsInSubGroup(subgroup)) do 
      tinsert(UNSORTED_RAID_GROUP[subgroup], player)
   end
end
```

Then change `getSortedRaidGroup` 

```
table.sort(SORTED_RAID_GROUP,
   ... rest of logic

=>

for _, subgroup in pairs(SORTED_RAID_GROUP) do
   table.sort(subgroup,
   ... rest of logic
end
```

then in `updateRaidFrames` you would do something like this

```
for i = 1, #SORTED_RAID_GROUP do

=>

for subgroup, players in pairs(SORTED_RAID_GROUP) do
   -- get the proper header here
   local header
   if Cell.vars.currentLayoutTable["main"]["combineGroups"] then
        header = _G["CellRaidFrameHeader0"]
    else
        header = _G["CellRaidFrameHeader"..subgroup]
    end

   -- iterate over the players in the subgroup
   ... rest of logic
end
```

It's prolly a bit of paraphrasing that I'm doing and I might be skipping over some detail that I just miss since I've made the code :sweat_smile:

Let me know if it makes sense or if it sounds a bit unwieldy. Prolly got some time today to look at it myself if you'd rather want that.

**Comment by Krealle** [comment]
Yea looking at Cell fn

```
function F:GetUnitsInSubGroup(group)
    local units = {}
    for i = 1, GetNumGroupMembers() do
        -- name, rank, subgroup, level, class, fileName, zone, online, isDead, role, isML, combatRole = GetRaidRosterInfo(raidIndex)
        local name, _, subgroup = GetRaidRosterInfo(i)
        if subgroup == group then
            tinsert(units, "raid"..i)
        end
    end
    return units
end
```

Instead of calling their function we should just make our own version so we can use the `subgroup` var ourself to properly assign to the table.

If done like this, subgroup can potentially also be parsed to `getPlayerInfo` to save some string matching and api calls for cached info.

Maybe you could traverse the headers instead of this, hmm, maybe cursed.

**Comment by DarthWixon** [comment]
Thanks for looking into this, I've been out all day today, and won't likely be back til the weekend. I'm not in a rush to get this working but if you'd like to then please go ahead. If not I'll take a proper look again over the weekend/next week. I appreciate the comments as well, am completely new to Lua so all help is good :)

**Comment by Krealle** [comment]
Actually just pushed an update that implemented this.

Turned out to be a bit more involved to implement since lua sorting apparently gets a bit hissyfitty when you start doing it in 2D arrays :laughing:

**Pull request closed without merging**
